changelog:
  categories:
    - title: Breaking Changes 💥
      labels:
        - breaking 💥
        - breaking
    - title: Features 🎉
      labels:
        - feature ✨
        - feat
    - title: Bug Fixes 🐝
      labels:
        - fix 🐝
        - bug 🐝
        - fix
    - title: Performance ⚡
      labels:
        - performance ⚡
        - perf
    - title: Build 🔧
      labels:
        - build 🔧
        - build
    - title: Testing 🧪
      labels:
        - test 🧪
        - test
    - title: Security 🔒
      labels:
        - security 🔒
        - security
    - title: Documentation 📖
      labels:
        - documentation 📖
        - docs
    - title: Dependencies 🤖
      labels:
        - dependencies
        - dependencies 🤖
        - dependabot
    - title: Other Changes
      labels:
        - "*"
