name: Import F45 Lionheart Data to Strava 📊

on:
  workflow_dispatch:
    inputs:
      CLASS_DATE:
        description: "F45 Class Date (YYYY-MM-DD)"
        required: true
        default: "2023-01-01"
      CLASS_TIME:
        description: "F45 Class Time (HH:MM)"
        required: true
        default: "09:30"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Node.js script
        uses: JamesIves/f45-lionheart-strava-importer@main
        with:
          F45_CLASS_DATE: ${{ github.event.inputs.CLASS_DATE }}
          F45_CLASS_TIME: ${{ github.event.inputs.CLASS_TIME }}
          F45_STUDIO_CODE: ${{ secrets.F45_STUDIO_CODE }}
          F45_USER_ID: ${{ secrets.F45_USER_ID }}
          F45_LIONHEART_SERIAL_NUMBER: ${{ secrets.F45_LIONHEART_SERIAL_NUMBER }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
